export const REQUEST: string = "REQUEST";
export const USER_SUCCESS: string = "USER_SUCCESS";
export const USER_FAILED: string = "USER_FAILED";

export const BLOG_LIST_ERROR = "BLOG_LIST_ERROR";
export const BLOG_LIST_REMOVE_SUCCESS = "BLOG_LIST_REMOVE_SUCCESS";
export const BLOG_LIST_REQUEST = "BLOG_LIST_REQUEST";
export const BLOG_LIST_SUCCESS = "BLOG_LIST_SUCCESS";

// order SINGLE
export const BLOG_SINGLE_REQUEST = "BLOG_SINGLE_REQUEST";
export const BLOG_LIST_DELETE_SUCCESS = "BLOG_LIST_DELETE_SUCCESS";
export const BLOG_LIST_CREATE_SUCCESS = "BLOG_LIST_CREATE_SUCCESS";
export const BLOG_SINGLE_SUCCESS = "BLOG_SINGLE_SUCCESS";
export const BLOG_SINGLE_ERROR = "BLOG_SINGLE_ERROR";
